### PR TITLE
Changed AppVeyorBuild attributes on ProjectName to reference Project Slug

### PR DESCRIPTION
**Pull request by somewhatabstract**
This is to address issue #14.

Updated the attributes for the `ProjectName` property of `AppVeyorBuild` to the project slug instead of name.

I did not rename the property itself as I believe that would unnecessarily break settings persistence for those already using this extension.

### CODE REVIEW

**Comment by AlonAm** [comment]
How do I find my projects slug? is it written in the UI?

**Comment by somewhatabstract** [comment]
It's the last part of the URL when you click a project.

**Comment by AlonAm** [comment]
Yes I figured that out.
I'm still thinking about this, whether to keep the Name and replace dots with dashes or use Slug like proposed. One thing i noticed thanks to you, it is not guaranteed that the Name and Slug will be the same. for example if you change a project name on AppVeyor.

**Comment by somewhatabstract** [comment]
Yeah, I figured using the slug from the URL is the easiest change that will
work

**Comment by AlonAm** [comment]
My conclusion is to add a new property called Slug in addition to Project Name.
There will be a temporary code that will upgrade existing user settings during startup.
A few versions later, I will remove the upgrade code and the Project Name property.

What's your opinion?

**Comment by somewhatabstract** [comment]
Seems fair to me. I mean, what it gets persisted as and what it appears as in the UX are really two different things. While in a perfect world, it persists under the exact same thing, I don't think it matters so much if it doesn't.

**Comment by AlonAm** [comment]
thanks a lot for reporting this issue and for the effort of creating that pull request.
I released that fix in 0.8.23 today and started work on 0.9 which will include some of your other requests.

**Pull request closed without merging**
